// Environment Configuration
// This file can be dynamically generated by your build process or server
// to inject environment-specific variables

window.MSA_ENV = {
  // API Configuration from environment variables
  API_URL: undefined, // Will be set by build process: process.env.MSA_API_URL
  API_KEY: undefined, // Will be set by build process: process.env.MSA_API_KEY
  
  // Environment info
  ENVIRONMENT: undefined, // 'development', 'staging', 'production'
  VERSION: undefined,     // Application version
  BUILD_TIME: undefined,  // Build timestamp
  
  // Feature flags from environment
  ENABLE_DEBUG: false,
  ENABLE_ANALYTICS: false
};

// Example build script replacement:
// This file can be processed by your build system to replace values like:
// API_URL: "%%MSA_API_URL%%"  -> API_URL: "https://api.utmmsa.com"
// API_KEY: "%%MSA_API_KEY%%"  -> API_KEY: "prod-key-12345"

// Development helper - remove in production
if (window.location.hostname === 'localhost') {
  console.log('🔧 MSA Environment Config Loaded', window.MSA_ENV);
}
