// Environment Configuration
// This file can be dynamically generated by your build process or server
// to inject environment-specific variables

window.MSA_ENV = {
  // API Configuration from environment variables
  // Set these values to override the default API configuration
  API_URL: undefined, // e.g., "https://api.utmmsa.com"
  API_KEY: undefined, // e.g., "your-production-key"
  
  // Environment info
  ENVIRONMENT: undefined, // 'development', 'staging', 'production'
  VERSION: undefined,     // Application version
  BUILD_TIME: undefined,  // Build timestamp
  
  // Feature flags from environment
  ENABLE_DEBUG: false,
  ENABLE_ANALYTICS: false
};

// Example: To set a custom API URL, uncomment and modify this line:
window.MSA_ENV.API_URL = "https://50c0ac0143b3.ngrok-free.app";

// Example: To set a custom API key, uncomment and modify this line:
// window.MSA_ENV.API_KEY = "your-secret-key";

// Development helper - logs configuration in development
if (window.location.hostname === 'localhost') {
  console.log('🔧 MSA Environment Config Loaded', window.MSA_ENV);
  console.log('📡 Current API URL will be determined by config.js');
}
